# Generated by Django 4.2 on 2023-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_alter_attendence_management_att_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_management',
            name='Att_Status',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
