# Generated by Django 4.2.1 on 2023-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Management',
            fields=[
                ('Alumni_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alumni_management',
            },
        ),
        migrations.CreateModel(
            name='Faculty_Management',
            fields=[
                ('Faculty_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID', models.TextField(max_length=100)),
                ('Full_Name', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.TextField(max_length=100)),
                ('Preferred_Subject', models.TextField(max_length=100)),
                ('Profile', models.FileField(upload_to='Images')),
                ('Faculty_Password', models.TextField(max_length=4)),
            ],
            options={
                'db_table': 'faculty_management',
            },
        ),
        migrations.CreateModel(
            name='Learning_Management',
            fields=[
                ('Learning_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'learning_management',
            },
        ),
        migrations.CreateModel(
            name='Library_Management',
            fields=[
                ('Library_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(max_length=100)),
                ('Author_Name', models.TextField(max_length=100)),
                ('Publisher_Name', models.TextField(max_length=100)),
                ('Preferred_Name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'library_management',
            },
        ),
        migrations.CreateModel(
            name='Marks_Management',
            fields=[
                ('Marks_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Profile', models.FileField(upload_to='Images')),
                ('Student_Name', models.TextField(max_length=100)),
                ('Student_Roll_No', models.TextField(max_length=100)),
                ('Add_Marks', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'marks_management',
            },
        ),
        migrations.CreateModel(
            name='Student_Management',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Full_Name', models.TextField(max_length=100)),
                ('Roll_No', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Branch_Name', models.TextField(max_length=100)),
                ('Semester', models.TextField(max_length=100)),
                ('Address', models.TextField(max_length=100)),
                ('Phone_No', models.TextField(max_length=10)),
                ('Profile', models.FileField(upload_to='Images')),
                ('Student_Password', models.TextField(max_length=4)),
            ],
            options={
                'db_table': 'student_management',
            },
        ),
        migrations.CreateModel(
            name='Subject_Management',
            fields=[
                ('Subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject_Name', models.TextField(max_length=100)),
                ('Branch_Name', models.TextField(max_length=100)),
                ('Semester', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'subject_management',
            },
        ),
        migrations.CreateModel(
            name='Thesis_Management',
            fields=[
                ('Thesis_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'thesis_management',
            },
        ),
    ]
