# Generated by Django 4.2.1 on 2023-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_management',
            name='Course_Name',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learning_management',
            name='Description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learning_management',
            name='Photo',
            field=models.FileField(null=True, upload_to='Images'),
        ),
        migrations.AddField(
            model_name='learning_management',
            name='Price',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
