# Generated by Django 4.2.1 on 2023-05-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alumni_management_student_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_management',
            old_name='ID',
            new_name='F_ID',
        ),
    ]
