# Generated by Django 4.2.1 on 2023-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_id_faculty_management_f_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_management',
            name='Student_Branch',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marks_management',
            name='Student_Semester',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marks_management',
            name='Student_Subject',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
