# Generated by Django 4.2.1 on 2023-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_marks_management_student_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks_management',
            name='Add_Marks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
