# Generated by Django 4.2.1 on 2023-05-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_marks_management_add_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_management',
            name='Student_Name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
