# Generated by Django 4.2.1 on 2023-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alumni_management_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_management',
            name='Alumni',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
