# Generated by Django 4.2.1 on 2023-05-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_student_management_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_management',
            name='Alumni',
            field=models.TextField(default='Not-Alumni', null=True),
        ),
    ]
