# Generated by Django 4.2.1 on 2023-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_faculty_management_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_management',
            name='Status',
            field=models.TextField(default='pending', null=True),
        ),
    ]
