# Generated by Django 4.2.1 on 2023-05-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_student_management_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_management',
            name='Faculty',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
