# Generated by Django 4.2.1 on 2023-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_subject_management_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_management',
            name='Subject',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
