# Generated by Django 4.2.1 on 2023-05-31 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_student_management_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_management',
            name='Stu_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.student_management'),
        ),
    ]
