# Generated by Django 4.2.1 on 2023-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_student_management_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_management',
            name='Marks_Subject',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
