# Generated by Django 4.2 on 2023-06-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_remove_marks_management_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_management',
            name='Att_Date',
            field=models.DateField(null=True),
        ),
    ]
