# Generated by Django 4.2 on 2023-06-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_remove_student_management_marks_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Buy_Model',
            fields=[
                ('Buy_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Student_Name', models.TextField(max_length=40)),
                ('Stundent_Roll_num', models.TextField(max_length=40)),
                ('Student_Branch', models.TextField(max_length=40)),
            ],
            options={
                'db_table': 'buy_course',
            },
        ),
    ]
