# Generated by Django 4.2 on 2023-06-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_course_buy_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_buy_model',
            name='CourseName',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='course_buy_model',
            name='Description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='course_buy_model',
            name='Price',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
