# Generated by Django 4.2 on 2023-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_course_buy_model_coursename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_management',
            name='Grade',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
