# Generated by Django 4.2 on 2023-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_alter_grade_management_add_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_management',
            name='Grade',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
